UPSTREAM: clk: rockchip: fix coding style for clk-cpu.c
Fix the issue reported by checkpatch:
ERROR: space prohibited before that ',' (ctx:WxW)
+               writel(clksel->val , cpuclk->reg_base + clksel->reg);

Signed-off-by: Shawn Lin <shawn.lin@rock-chips.com>
Signed-off-by: Heiko Stuebner <heiko@sntech.de>

(cherry picked from git.kernel.org mmind/linux-rockchip.git v4.6-clk/next
 commit fc6d875ecb83cd03afad4486c97a9355e00c8944)
Signed-off-by: Caesar Wang <wxt@rock-chips.com>